"""empty message

Revision ID: b576b8494784
Revises: 
Create Date: 2020-03-29 23:02:28.288192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b576b8494784'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_user_id'), 'rent', ['user_id'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reservation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('rent_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_user_id'), 'reservation', ['user_id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=True),
    sa.Column('rent_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['item_type.id'], ),
    sa.ForeignKeyConstraint(['rent_id'], ['rent.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item_type_id'), 'item', ['item_type_id'], unique=False)
    op.create_index(op.f('ix_item_rent_id'), 'item', ['rent_id'], unique=False)
    op.create_index(op.f('ix_item_reservation_id'), 'item', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_reservation_id'), table_name='item')
    op.drop_index(op.f('ix_item_rent_id'), table_name='item')
    op.drop_index(op.f('ix_item_item_type_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_reservation_user_id'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_rent_user_id'), table_name='rent')
    op.drop_table('rent')
    op.drop_table('user')
    op.drop_table('item_type')
    # ### end Alembic commands ###
